//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBotBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public int Id { get; set; }
        public string Msg { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ReviewTime { get; set; }
    }
}
